include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat anything we lint as a build break, not a suggestion.
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_redundant_argument_values
    - cancel_subscriptions
    - directives_ordering
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
